import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=mkdtempSync(path.join(tmpdir(),'marco-test-'));
const base='http://localhost:3124';
const initial='Test-only-password-93-strong!';
let app,cookie='',run=0;
async function boot(){Object.assign(process.env,{HOST:'127.0.0.1',PORT:'3124',APP_ORIGIN:base,DATA_DIR:data,ADMIN_PASSWORD:initial});app=await import(`../server.mjs?test=${++run}`);if(!app.server.listening)await new Promise((resolve,reject)=>{app.server.once('listening',resolve);app.server.once('error',reject);});}
async function stop(){if(app){await new Promise(resolve=>{app.server.close(resolve);app.server.closeAllConnections();});app.db.close();app=null;}}
function request(route,method='GET',data,auth=true,extra={}){return fetch(base+route,{method,headers:{Connection:'close',Origin:base,...(data?{'Content-Type':'application/json'}:{}),...(auth&&cookie?{Cookie:cookie}:{}),...extra},body:data?JSON.stringify(data):undefined});}
test('Landing y CMS: autenticación, contenido, imágenes, consultas y persistencia',async t=>{
  await boot();
  try{
    await t.test('Archivos públicos y datos privados',async()=>{assert.equal((await request('/')).status,200);assert.equal((await request('/assets/marco-zarate.jpg')).status,200);assert.equal((await request('/data/site.sqlite')).status,404);assert.equal((await request('/api/admin/inquiries')).status,401);});
    await t.test('Credenciales y protección de origen',async()=>{assert.equal((await request('/api/login','POST',{username:'admin',password:'wrong'})).status,401);assert.equal((await request('/api/login','POST',{username:'admin',password:initial},false,{Origin:'https://evil.example'})).status,403);const response=await request('/api/login','POST',{username:'admin',password:initial});assert.equal(response.status,200);cookie=response.headers.get('set-cookie').split(';')[0];assert.match(response.headers.get('set-cookie'),/HttpOnly/);assert.match(response.headers.get('set-cookie'),/SameSite=Strict/);});
    let content,version;
    await t.test('Guardar contenido y avisar en tiempo real',async()=>{({json:content,version}=await(await request('/api/content')).json());content=JSON.parse(content);content.hero.title='Título persistente de prueba';const controller=new AbortController();const stream=await fetch(base+'/api/events',{signal:controller.signal});const reader=stream.body.getReader();await reader.read();const saved=await request('/api/admin/content','PUT',{content,version});assert.equal(saved.status,200);const event=await reader.read();assert.match(new TextDecoder().decode(event.value),/changed/);controller.abort();assert.equal((await request('/api/admin/content','PUT',{content,version})).status,409);version++;const invalid=structuredClone(content);invalid.footer.socials=[{label:'Ataque',url:'javascript:alert(1)'}];assert.equal((await request('/api/admin/content','PUT',{content:invalid,version})).status,400);});
    await t.test('Subir imagen y validar formato',async()=>{const jpg=readFileSync(path.join(root,'public/assets/marco-zarate.jpg'));const response=await fetch(base+'/api/admin/images',{method:'POST',headers:{Connection:'close',Origin:base,Cookie:cookie,'Content-Type':'image/jpeg'},body:jpg});assert.equal(response.status,201);const {url}=await response.json();assert.equal((await request(url)).headers.get('content-type'),'image/jpeg');content.identity.photo=url;assert.equal((await request('/api/admin/content','PUT',{content,version})).status,200);const invalid=await fetch(base+'/api/admin/images',{method:'POST',headers:{Connection:'close',Origin:base,Cookie:cookie},body:'<svg onload="alert(1)"></svg>'});assert.equal(invalid.status,415);});
    await t.test('Validar y recibir consulta',async()=>{const payload={name:'Persona de prueba',email:'test@example.com',phone:'3511234567',message:'Consulta de prueba <script>alert(1)</script>',website:'',consent:true};assert.equal((await request('/api/contact','POST',{...payload,consent:false},false)).status,400);assert.equal((await request('/api/contact','POST',payload,false)).status,201);const rows=await(await request('/api/admin/inquiries')).json();assert.equal(rows.length,1);assert.equal(rows[0].message,payload.message);});
    await t.test('Persistencia después de reiniciar',async()=>{await stop();await boot();const saved=JSON.parse((await(await request('/api/content')).json()).json);assert.equal(saved.hero.title,'Título persistente de prueba');assert.equal((await request(saved.identity.photo)).status,200);assert.equal((await(await request('/api/admin/inquiries')).json()).length,1);});
    await t.test('Cambiar contraseña revoca sesiones',async()=>{assert.equal((await request('/api/admin/password','POST',{current:initial,next:'New-test-password-91-secure!'})).status,200);assert.equal((await request('/api/admin/session')).status,401);assert.equal((await request('/api/login','POST',{username:'admin',password:initial})).status,401);const login=await request('/api/login','POST',{username:'admin',password:'New-test-password-91-secure!'});assert.equal(login.status,200);cookie=login.headers.get('set-cookie').split(';')[0];const rows=await(await request('/api/admin/inquiries')).json();assert.equal((await request('/api/admin/inquiries/'+rows[0].id,'DELETE')).status,200);assert.equal((await(await request('/api/admin/inquiries')).json()).length,0);assert.equal((await request('/api/admin/logout','POST',{})).status,200);assert.equal((await request('/api/admin/session')).status,401);});
  }finally{await stop();rmSync(data,{recursive:true,force:true});}
});

